package com.workshop.companydata;

/**
 * This class was automatically generated by the data modeler tool.
 */

@javax.persistence.Entity
@javax.persistence.Table(name = "companydata")
public class CompanyData
		extends
			org.drools.persistence.jpa.marshaller.VariableEntity
		implements
			java.io.Serializable {

	static final long serialVersionUID = 1L;

	@javax.persistence.GeneratedValue(generator = "COMPANYDATA_ID_GENERATOR", strategy = javax.persistence.GenerationType.AUTO)
	@javax.persistence.Id
	@javax.persistence.SequenceGenerator(name = "COMPANYDATA_ID_GENERATOR", sequenceName = "COMPANYDATA_ID_SEQ")
	private java.lang.Long id;

	@org.kie.api.definition.type.Label("Product")
	private java.lang.String product;

	@org.kie.api.definition.type.Label("Client id")
	private java.lang.String clientId;

	@org.kie.api.definition.type.Label("Client Full Name")
	private java.lang.String clienFuilName;

	@org.kie.api.definition.type.Label("Account Client Number")
	private java.lang.String acconuntClientNumber;

	@org.kie.api.definition.type.Label("Externa lCase Id")
	private java.lang.String externalCaseId;

	@org.kie.api.definition.type.Label("User identifier")
	private java.lang.String userId;

	@org.kie.api.definition.type.Label("BranchCode")
	private java.lang.String branchCode;

	public CompanyData() {
	}

	public java.lang.Long getId() {
		return this.id;
	}

	public void setId(java.lang.Long id) {
		this.id = id;
	}

	public java.lang.String getProduct() {
		return this.product;
	}

	public void setProduct(java.lang.String product) {
		this.product = product;
	}

	public java.lang.String getClientId() {
		return this.clientId;
	}

	public void setClientId(java.lang.String clientId) {
		this.clientId = clientId;
	}

	public java.lang.String getClienFuilName() {
		return this.clienFuilName;
	}

	public void setClienFuilName(java.lang.String clienFuilName) {
		this.clienFuilName = clienFuilName;
	}

	public java.lang.String getAcconuntClientNumber() {
		return this.acconuntClientNumber;
	}

	public void setAcconuntClientNumber(java.lang.String acconuntClientNumber) {
		this.acconuntClientNumber = acconuntClientNumber;
	}

	public java.lang.String getExternalCaseId() {
		return this.externalCaseId;
	}

	public void setExternalCaseId(java.lang.String externalCaseId) {
		this.externalCaseId = externalCaseId;
	}

	public java.lang.String getUserId() {
		return this.userId;
	}

	public void setUserId(java.lang.String userId) {
		this.userId = userId;
	}

	public java.lang.String getBranchCode() {
		return this.branchCode;
	}

	public void setBranchCode(java.lang.String branchCode) {
		this.branchCode = branchCode;
	}

	public CompanyData(java.lang.Long id, java.lang.String product,
			java.lang.String clientId, java.lang.String clienFuilName,
			java.lang.String acconuntClientNumber,
			java.lang.String externalCaseId, java.lang.String userId,
			java.lang.String branchCode) {
		this.id = id;
		this.product = product;
		this.clientId = clientId;
		this.clienFuilName = clienFuilName;
		this.acconuntClientNumber = acconuntClientNumber;
		this.externalCaseId = externalCaseId;
		this.userId = userId;
		this.branchCode = branchCode;
	}

}