package com.workshop.companydata;

/**
 * This class was automatically generated by the data modeler tool.
 */

public class EmptyObject implements java.io.Serializable {

    static final long serialVersionUID = 1L;

    public EmptyObject() {
    }




}